### PR TITLE
feat: init LAPIS v2

### LINKED ISSUE #121: Setup Spring app for v2
Build the foundation for the LAPIS v2 app:
* Kotlin
* Gradle
* Spring Boot
* Implement one endpoint (`/aggregated`) that returns a hardcoded response

### PR DESCRIPTION
**Pull request by fengelniederhammer**
resolves #121

### CODE REVIEW

**Review by chaoran-chen — CHANGES_REQUESTED** [review]
Looks good to me! Just one change request: let's use `org.genspectrum` instead of `ch.ethz` (in  the past, CoV-Spectrum was hosted at a subdomain of ethz.ch but that's outdated now).

**Comment by fengelniederhammer** [comment]
Should we keep the `lapis2` in the package name? Or simply rename it to `lapis`?

**Comment by chaoran-chen** [comment]
Just `lapis`

**Review by chaoran-chen — APPROVED** [review]
Great, thanks!

**Comment by fengelniederhammer** [comment]
Now we have `org.genspectrum.lapis`. I'd keep the gradle project name as lapisv2 for now though to distinguish it from the old LAPIS. And this is a lot easier to change later.

**Pull request merged**
