### PR TITLE
docs(root): document that regex support in LAPIS (as of 0.2.10) requires at least SILO 0.2.14

### PR DESCRIPTION
**Pull request by fengelniederhammer**
## PR Checklist
- [x] All necessary documentation has been adapted.
~~- [ ] The implemented feature is covered by an appropriate test.~~

### CODE REVIEW

**Review by JonasKellerer — APPROVED** [review]
LGTM, appart from the changelog preview.

**Comment by JonasKellerer** [comment]
Reminder: We might need to change this after version 0.3

**Comment by fengelniederhammer** [comment]
> Reminder: We might need to change this after version 0.3

What do we need to change?

**Comment by JonasKellerer** [comment]
Ah, its also higher versions. Sry.

**Pull request merged**
